name: healthnode
description: Full functional project for HealthNode.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.0.0      
  firebase_auth: ^5.0.0     
  cloud_firestore: ^5.0.0   
  firebase_storage: ^12.0.0 
  # AI এরর ফিক্স করতে ভার্সন আপডেট করা হয়েছে
  google_generative_ai: ^0.4.4
  image_picker: ^1.1.2        
  geolocator: ^13.0.1   
  intl: ^0.19.0         
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true